In [15]:
import numpy as np

# Task 1
arr1 = np.arange(1, 11) #массив от 1 до 10
arr2 = np.random.randint(1, 10, (3, 3))
print(arr1)
print()
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]

[[3 4 3]
 [5 6 6]
 [9 3 6]]


In [16]:
# Task 2
print("Сумма:", arr1.sum())
print("Среднее:", arr1.mean())
print("Максимум:", arr1.max())

arr1 = arr1 * 2

for i in range(len(arr1)):
    if arr1[i] > 5:
        arr1[i] = 0


print("Новый:", arr1)

Сумма: 55
Среднее: 5.5
Максимум: 10
Новый: [2 4 0 0 0 0 0 0 0 0]
